# Generated by Django 5.2 on 2025-04-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('lawyer', 'Lawyer'), ('court', 'Court')], default='client', max_length=6),
        ),
    ]
