# Generated by Django 5.2 on 2025-04-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_remove_user_role_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='encrypted_file_path',
            new_name='cid',
        ),
        migrations.RemoveField(
            model_name='file',
            name='original_file_name',
        ),
    ]
